# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d5696c37c062d315292488a69bc7ffe009204c4eb505ae0f3f3d0350f18509db6429fb8bf4bfa04ebc2fd44c6ed23c434a5b2fc67163fb3d38e33394462751

test:
  secret_key_base: 61c8876c95091a43c2e57def3444e41cfb4579c4bf44c3d4da28081b86c01794dd5d945621e66e98507050ec23671e68cd3634eb35cd8febf9714e994532074c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
